version: 1
disable_existing_loggers: False

formatters:
  standard:
    format: "%(asctime)s [%(levelname)s] %(name)s: %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"
  
  detailed:
    format: "%(asctime)s [%(levelname)s] %(name)s - %(filename)s:%(lineno)d - %(funcName)s(): %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"
  
  simple:
    format: "[%(levelname)s] %(message)s"

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: standard
    stream: ext://sys.stdout
  
  file:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: detailed
    filename: ../logs/app.log
    maxBytes: 10485760  # 10MB
    backupCount: 5
    encoding: utf8
  
  error_file:
    class: logging.handlers.RotatingFileHandler
    level: ERROR
    formatter: detailed
    filename: ../logs/error.log
    maxBytes: 10485760  # 10MB
    backupCount: 5
    encoding: utf8

loggers:
  # 项目特定的logger
  proj:
    level: DEBUG
    handlers: [console, file, error_file]
    propagate: False
  
  # 第三方库的logger（可选）
  requests:
    level: WARNING
    handlers: [console]
    propagate: False
  
  urllib3:
    level: WARNING
    handlers: [console]
    propagate: False

root:
  level: INFO
  handlers: [console, file]

# 自定义配置
custom:
  log_dir: "logs"
  max_file_size: 10485760  # 10MB
  backup_count: 5
  date_format: "%Y-%m-%d %H:%M:%S"
